name: Deployment pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
      
jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Redudant Builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
  lint:
    needs: [install]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint

  build:
    needs: [install]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: '16'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: '16'
    - name: Install dependencies
      run: npm ci
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Test
      run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to Vercel
        if: ${{ github.event_name == 'push' }}
        uses: amondnet/vercel-action@v20 
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}} 
          working-directory: dist
