name: Deployment pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
      
jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redudant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
  lint:
    needs: [install]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint

  build:
    needs: [install]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  # test:
    # needs: [lint, build]
    # runs-on: ubuntu-22.04
    # steps:
    # - uses: actions/checkout@v4
      # with:
        # fetch-depth: 0
    # - uses: actions/setup-node@v4
      # with:
        # cache: 'npm'
        # node-version-file: '.nvmrc'
    # - name: Install dependencies
      # run: npm ci
    # - uses: actions/download-artifact@v4
      # with:
        # name: dist
        # path: dist
    # - name: Test
      # run: npm test

  deploy:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Deploy to Vercel
        if: ${{ github.event_name == 'push' }}
        uses: amondnet/vercel-action@v20 
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}} 
          working-directory: dist
